package model.builder.ui

import javax.swing.JFrame
import javax.swing.JTable

import static java.util.Arrays.asList

Vector<String> columns = new Vector<>(asList("Name", "E-Mail", "Age"))
Vector<Vector<String>> rows = new Vector<>(asList(
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
        ["Anthony Bargnesi", "abargnesi@gmail.com", "32"] as Vector<String>,
        ["Kate Bargnesi", "kate.bargnesi@gmail.com", "32"] as Vector<String>,
));

JTable table = new JTable(rows, columns)
TableScrollable tscroll = new TableScrollable(table)

JFrame frame = new JFrame("Test")
frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE
frame.getContentPane().add(tscroll)
frame.visible = true